### ISSUE TITLE
Remote host forcibly closed

### ISSUE THREAD

**Issue by zachup100** [MaximumADHD/Roblox-Studio-Mod-Manager#144]
I've been using your Studio Manager for some time now but I had to reinstall Windows 11 recently due to a major bug. However, since this new installation of Studio Manager, it seems to fail to obtain some detail. It results in the 'An existing connection was forcibly closed by the remote' message. I've tried this a few times, and I did a few days ago just in-case it was some connection issue but still occurs.

Unless there is some dependency I am missing, I am not sure how to fix this. I've tried the LIVE and zQtitanStudioRelease build.
On top of that, even if it fails and I relaunch Studio. It loads into a weird older version with some red boxes, assuming those are missing icons. I am using a classimage replacement image.

Running Windows 11 Pro Build 22000.918 with
AMD Ryzen 5 2600
Nvidia GeForce RTX 3060

[Edit: Just seen the other post about this similar issue]
I have a near bare bone version of Windows, I am just using the default Windows Defender. I normally use BitDefender but haven't reinstalled it.

![image](https://user-images.githubusercontent.com/1534792/189484674-ee25d9ff-12dd-48b6-89a5-bdaae729a73b.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RobloxStudioModManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Robert/AppData/Local/Roblox%20Studio%20Mod%20Manager/RobloxStudioModManager.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Robert/AppData/Local/Roblox%20Studio%20Mod%20Manager/RobloxStudioModManager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
RobloxDeployHistory
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Robert/AppData/Local/Roblox%20Studio%20Mod%20Manager/RobloxStudioModManager.exe
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
Konscious.Security.Cryptography.Blake2
    Assembly Version: 1.0.9.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Robert/AppData/Local/Roblox%20Studio%20Mod%20Manager/RobloxStudioModManager.exe
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Robert/AppData/Local/Roblox%20Studio%20Mod%20Manager/RobloxStudioModManager.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by randomizednum** [comment]
[I had](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/134) a similar issue, [many](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/109) [others](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/issues/127) did too. Are you sure you're using the newest version? For me, a recent version fixed it.

**Comment by zachup100** [comment]
> 

I am indeed, I even tried downgrading versions to see if it was fixed but I am still having that issue. I did mention I recently re-installed windows so I'm not sure if I am missing a dependency or something.

**Comment by PlayerValley** [comment]
bumping this because it also occured to me
![image](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/58902624/f9075779-ede7-4e5c-935f-6c66ca64d56b)

**Comment by MildilyAcidic** [comment]
![NVIDIA_Share_BV05OcmIQh](https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/assets/110824257/7c116e0c-7d51-487f-a615-3a258c11ac4b)
bumping
