### ISSUE TITLE
Crash after updating

### ISSUE THREAD

**Issue by medallyon** [MaximumADHD/Roblox-Studio-Mod-Manager#162]
As part of the most recent updates on the LIVE channel, after updating Studio, it crashes with the following messages. It also happens when I force re-install.

![image](https://user-images.githubusercontent.com/17483199/228479635-0143989a-b2f1-474b-abd8-9c8b21a4de0e.png)

```
************** Exception Text **************
System.IO.InvalidDataException: RobloxStudioLauncherBeta.exe expected packed size: 2066048 but got: 2065536
   at RobloxStudioModManager.StudioBootstrapper.<installPackage>d__103.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RobloxStudioModManager.StudioBootstrapper.<>c__DisplayClass107_1.<<Bootstrap>b__8>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at RobloxStudioModManager.StudioBootstrapper.<Bootstrap>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RobloxStudioModManager.BootstrapperForm.<Bootstrap>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RobloxStudioModManager.Launcher.<launchStudio_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by robocu3** [comment]
I have the same issue
